### PR TITLE
Packet.net deployment for benchmarking 1.1.0-beta-2

### PR DESCRIPTION
**Pull request by katia-e**
Prior to merging with 1.1.0-beta2 #465 has to be merged

### CODE REVIEW

**Comment by GlenDC** [comment]
Will review this once #465 is merged into beta-2.

**Comment by katia-e** [comment]
`packets_beta2` is rebased on `1.1.0-beta-2` after merging 465. 
I'm currently fixing one more bug that appears in `packets_beta2`
```
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
```
It appears because we use a number of threads to run `packet.net` devices in parallel, and apparently not using correctly.

**Comment by GlenDC** [comment]
@katia-e travis ci tests are failing...

**Comment by katia-e** [comment]
Even though currently benchmark deployment at `packet.net` works, while installing `zstor` on packet.net with `prefab` some errors appear in logs like (more complete log:
[install_errors.txt](https://github.com/zero-os/0-stor/files/1686374/install_errors.txt)
)
``` bash
[19.6 kB]
[Thu01 17:44] - SSHClient.py        :272 :j.ssh client: 147.75.82.35(22): - DEBUG    - Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 git-man all 1:2.7.4-0ubuntu1.3 [736 kB]
[Thu01 17:44] - SSHClient.py        :277 :j.ssh client: 147.75.82.229(22): - ERROR    - github.com/tools/godep/vendor/github.com/kr/fs
[Thu01 17:44] - SSHClient.py        :277 :j.ssh client: 147.75.82.229(22): - ERROR    - github.com/tools/godep/vendor/github.com/kr/text
[Thu01 17:44] - SSHClient.py        :277 :j.ssh client: 147.75.82.229(22): - ERROR    - github.com/tools/godep/vendor/github.com/pmezard/go-difflib/difflib
[Thu01 17:44] - SSHClient.py        :277 :j.ssh client: 147.75.82.229(22): - ERROR    - github.com/tools/godep/vendor/golang.org/x/tools/go/vcs
[Thu01 17:44] - SSHClient.py        :277 :j.ssh client: 147.75.82.229(22): - ERROR    - github.com/tools/godep/vendor/github.com/kr/pretty
[Thu01 17:44] - SSHClient.py        :272 :j.ssh client: 147.75.82.35(22): - DEBUG    - Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 git amd64 1:2.7.4-0ubuntu1.3 [3,102 kB]
[Thu01 17:44] - SSHClient.py        :272 :j.ssh client: 147.75.82.35(22): - DEBUG    - Get:4 http://archive.ubuntu.com/ubuntu xenial/main amd64 patch amd64 2.7.5-1 [90.4 kB]
[Thu01 17:44] - SSHClient.py        :277 :j.ssh client: 147.75.82.229(22): - ERROR    - github.com/tools/godep
```

**Comment by katia-e** [comment]
Currently benchmark is running successfully on `packet.net` only if we provision devices only ones in the beginning of the benchmark. In case if I start and remove `packet.net` device for each benchmark, I receive an error while provisioning devices for the second time:
``` bash
[Fri02 18:43] - PacketNetFactory.py :206 :j.clients.packetnet            - DEBUG    - provisioning
[Fri02 18:43] - PacketNetFactory.py :206 :j.clients.packetnet            - DEBUG    - provisioning
[Fri02 18:43] - PacketNetFactory.py :206 :j.clients.packetnet            - DEBUG    - provisioning
[Fri02 18:43] - PacketNetFactory.py :206 :j.clients.packetnet            - DEBUG    - provisioning
[Fri02 18:43] - PacketNetFactory.py :206 :j.clients.packetnet            - DEBUG    - provisioning
[Fri02 18:43] - PacketNetFactory.py :206 :j.clients.packetnet            - DEBUG    - active
[Fri02 18:43] - PacketNetFactory.py :213 :j.clients.packetnet            - INFO     - ipaddress found = 147.75.102.207
[Fri02 18:43] - NetTools.py         :71  :j.sal.nettools                 - DEBUG    - test tcp connection to '147.75.102.207' on port 22
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "test_deployment.py", line 9, in <module>
    node = client.startDevice(hostname=hostname, facility='ams1', plan="baremetal_0", os="ubuntu_16_04")
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/packetnet/PacketNetFactory.py", line 144, in startDevice
    wait=wait, remove=remove, ipxeUrl=ipxeUrl, zerotierId=zerotierId, always_pxe=False)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/packetnet/PacketNetFactory.py", line 220, in _startDevice
    ssh.execute("ls /")
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 233, in execute
    ch = self.transport.open_session()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 732, in open_session
    timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 856, in open_channel
    raise e
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 1821, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 423, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 274, in read_all
    x = self.__socket.recv(n)
ConnectionResetError: [Errno 104] Connection reset by peer
[Errno 104] Connection reset by peer
```

This error I also can reproduce without benchmark code, just by running the script (errors at the third loop):
``` python
from js9 import j 

hostname = "testB"

for i in range(3):   
    client = j.clients.packetnet.get()
    node = client.startDevice(hostname=hostname, facility='ams1', plan="baremetal_0", os="ubuntu_16_04")
    node.prefab.system.package.install("git")
    client.removeDevice(hostname)
    del client
```

Is it possible that the error comes from jumpscale, or I'm using it wrong?

**Comment by GlenDC** [comment]
@zaibon you see something wrong with that script of @katia-e?

**Comment by zaibon** [comment]
close for inactivity

**Pull request closed without merging**
