### PR TITLE
replace github.com/minio/blake2b-simd with golang.org/x/crypto/blake2b

### LINKED ISSUE #510: replace github.com/minio/blake2b-simd with golang.org/x/crypto/blake2b

### PR DESCRIPTION
**Pull request by zaibon**
closes #510 
results of benchmark before and after change of the lib:
```
benchmark                                               old ns/op     new ns/op     delta
BenchmarkSumBlake2b256/512-bytes-4                      1123          917           -18.34%
BenchmarkSumBlake2b256/4096-bytes-4                     7056          6565          -6.96%
BenchmarkSumBlake2b256/131072-bytes-4                   216805        207368        -4.35%
BenchmarkSumBlake2b512/512-bytes-4                      1153          929           -19.43%
BenchmarkSumBlake2b512/4096-bytes-4                     7167          6607          -7.81%
BenchmarkSumBlake2b512/131072-bytes-4                   216676        207697        -4.14%
BenchmarkSumBlake2b256er_WithoutKey/512-bytes-4         1105          960           -13.12%
BenchmarkSumBlake2b256er_WithoutKey/4096-bytes-4        7105          6676          -6.04%
BenchmarkSumBlake2b256er_WithoutKey/131072-bytes-4      217568        207869        -4.46%
BenchmarkSumBlake2b256er_WithoutKey/1048576-bytes-4     217467        207658        -4.51%
BenchmarkSumBlake2b256er_WithKey/512-bytes-4            1394          1195          -14.28%
BenchmarkSumBlake2b256er_WithKey/4096-bytes-4           7768          6876          -11.48%
BenchmarkSumBlake2b256er_WithKey/131072-bytes-4         218767        208060        -4.89%
BenchmarkSumBlake2b256er_WithKey/1048576-bytes-4        1752674       1660718       -5.25%
BenchmarkSumBlake2b512er_WithoutKey/512-bytes-4         1145          990           -13.54%
BenchmarkSumBlake2b512er_WithoutKey/4096-bytes-4        7080          6691          -5.49%
BenchmarkSumBlake2b512er_WithoutKey/131072-bytes-4      216759        207399        -4.32%
BenchmarkSumBlake2b512er_WithoutKey/1048576-bytes-4     1730830       1654038       -4.44%
BenchmarkSumBlake2b512er_WithKey/512-bytes-4            1436          1211          -15.67%
BenchmarkSumBlake2b512er_WithKey/4096-bytes-4           7371          6883          -6.62%
BenchmarkSumBlake2b512er_WithKey/131072-bytes-4         216894        208178        -4.02%
BenchmarkSumBlake2b512er_WithKey/1048576-bytes-4        1738029       1659043       -4.54%
```

### CODE REVIEW

**Comment by GlenDC** [comment]
Does the hardware you ran the benchmarks on support AVX2, @zaibon?

**Comment by zaibon** [comment]
> Does the hardware you ran the benchmarks on support AVX2, @zaibon?

Yes it does

I re-pushed a version after updated my dep tool, but it doesn't seems to have change the layout.

**Comment by GlenDC** [comment]
Alright, in that case let's just merge it as it is.

**Comment by zaibon** [comment]
Wait for travis, cause it seems it has some trouble

**Comment by zaibon** [comment]
Seems there is a problem because of https://github.com/zero-os/0-stor/pull/518/files#diff-bd247e83efc3c45ae9e8c47233249f18R270
Seesm the full crypto package is locked to a specific revision. I tried to change that, but then it lots of other stuff, which make me think that this specific revision is needed for grpc or another dependencies.

**Comment by GlenDC** [comment]
> Seems there is a problem because of https://github.com/zero-os/0-stor/pull/518/files#diff-bd247e83efc3c45ae9e8c47233249f18R270
Seesm the full crypto package is locked to a specific revision. I tried to change that, but then it lots of other stuff, which make me think that this specific revision is needed for grpc or another dependencies.

Not sure what you're talking about here, all I had to change was that you need to use the correct constructor provided by google's lib, rather than the lib we were using.

**Pull request merged**
