### PR TITLE
Benchmark orchestrator for beta-2

### PR DESCRIPTION
**Pull request by zaibon**

### CODE REVIEW

**Comment by GlenDC** [comment]
I would squash these commits big-time though, as the history is really still pretty raw. Also you have some conflicts.

Does this PR mean that the benchmark stuff is ready for review?

**Comment by katia-e** [comment]
@GlenDC 
I'm finishing changes in python part after rebase from master. After this the benchmark stuff is ready for review

**Comment by GlenDC** [comment]
Great, let me know once the PR is ready for review.

**Comment by katia-e** [comment]
PR #465 is open to merge benchmarking tools with beta-2

**Pull request closed without merging**
