### PR TITLE
Fix & improve Delete API:

### PR DESCRIPTION
**Pull request by iwanbk**
Part of #246 

- add DeleteWithMeta to deletes based on given metadata
- also delete the metadata
- add test

### CODE REVIEW

**Comment by iwanbk** [comment]
we suddenly got race condition in badger on travis build
https://travis-ci.org/zero-os/0-stor/jobs/277613081
```
=== RUN   TestCheck
time="2017-09-20T05:04:33Z" level=info msg="stop grpc server"
time="2017-09-20T05:04:33Z" level=info msg="closing database"
time="2017-09-20T05:04:33Z" level=info msg="stop grpc server"
time="2017-09-20T05:04:33Z" level=info msg="closing database"
time="2017-09-20T05:04:34Z" level=info msg="stop grpc server"
time="2017-09-20T05:04:34Z" level=info msg="closing database"
time="2017-09-20T05:04:34Z" level=info msg="stop grpc server"
time="2017-09-20T05:04:34Z" level=info msg="closing database"
--- PASS: TestCheck (2.92s)
=== RUN   TestRoundTripGRPC
=== RUN   TestRoundTripGRPC/simple-write
=== RUN   TestRoundTripGRPC/chunks
=== RUN   TestRoundTripGRPC/compress
=== RUN   TestRoundTripGRPC/encrypt
=== RUN   TestRoundTripGRPC/replication
time="2017-09-20T05:04:36Z" level=warning msg="replication read, error reading from 127.0.0.1:37102: rpc error: code = Unknown desc = Not found"
=== RUN   TestRoundTripGRPC/distribution
=== RUN   TestRoundTripGRPC/chunks-distribution
=== RUN   TestRoundTripGRPC/compress-encrypt
=== RUN   TestRoundTripGRPC/chunk-compress-encrypt
=== RUN   TestRoundTripGRPC/compress-encrypt-replication
=== RUN   TestRoundTripGRPC/compress-encrypt-distribution
=== RUN   TestRoundTripGRPC/chunks-compress-encrypt-replication
==================
WARNING: DATA RACE
Write at 0x00c4201cea24 by goroutine 302:
  github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*valueLog).write.func1()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/value.go:750 +0x4b2
  github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*valueLog).write()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/value.go:801 +0x88d
  github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*KV).writeRequests()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/kv.go:603 +0x2b3
  github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*KV).doWrites.func1()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/kv.go:643 +0x6f
Previous read at 0x00c4201cea24 by goroutine 464:
  github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*valueLog).Read()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/value.go:824 +0x194
  github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*KV).yieldItemValue()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/kv.go:419 +0x5f2
  github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*KVItem).Value()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/iterator.go:71 +0x16a
  github.com/zero-os/0-stor/server/db/badger.BadgerDB.Get()
      /home/travis/gopath/src/github.com/zero-os/0-stor/server/db/badger/badger.go:83 +0x1d1
  github.com/zero-os/0-stor/server/db/badger.(*BadgerDB).Get()
      <autogenerated>:1 +0x99
  github.com/zero-os/0-stor/server/manager.(*ObjectManager).Get()
      /home/travis/gopath/src/github.com/zero-os/0-stor/server/manager/object.go:65 +0x108
  github.com/zero-os/0-stor/server.(*ObjectAPI).Get()
      /home/travis/gopath/src/github.com/zero-os/0-stor/server/object_api.go:94 +0x206
  github.com/zero-os/0-stor/grpc_store._ObjectManager_Get_Handler()
      /home/travis/gopath/src/github.com/zero-os/0-stor/grpc_store/store.pb.go:767 +0x336
  github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).processUnaryRPC()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:781 +0x1095
  github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).handleStream()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:981 +0x14a6
  github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:551 +0xac
Goroutine 302 (running) created at:
  github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*KV).doWrites()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/kv.go:692 +0x44e
Goroutine 464 (finished) created at:
  github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:549 +0xb8
  github.com/zero-os/0-stor/vendor/google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/transport/http2_server.go:336 +0x1493
  github.com/zero-os/0-stor/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/transport/http2_server.go:403 +0xaad
  github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:547 +0x1d1
  github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).serveHTTP2Transport()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:540 +0x68c
  github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).handleRawConn()
      /home/travis/gopath/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:507 +0x5c6
```

will check it after lunch

**Comment by iwanbk** [comment]
As far as i can see:
- the race error is not related to this PR
- it seems to be a badger issue. but it also raise another questions : do we need to add some `Mutex` to avoid this race issue

One thing i noticed about `TestRoundTripGRPC` is that it use same `key` for all the tests.

What do you think @zaibon ?

**Comment by iwanbk** [comment]
updated badger, seemed to fix the error in my laptop for continuous `go test -run -race TestRoundTripGRPC` but still got error in travis, this time the errors is not clear (almost no error message)
https://gist.github.com/iwanbk/5ce035d7d8e124d2c2c78d8479526bcb

**Comment by zaibon** [comment]
This is strange, I see test failed for `github.com/zero-os/0-stor/client` but I see nothing wrong...
do we miss some logging to see the error ?

**Comment by zaibon** [comment]
@iwanbk can you also check the branch https://github.com/zero-os/0-stor/tree/cli_delete cause I also started working on #246, you can probably merge my branch into yours.

**Comment by iwanbk** [comment]
>  I see test failed for github.com/zero-os/0-stor/client but I see nothing wrong...

not sure what you mean, which error?
mine is race error.

> @iwanbk can you also check the branch https://github.com/zero-os/0-stor/tree/cli_delete cause I also started working on #246 

It seems your's is better, only need to add some unit test there.

**Comment by zaibon** [comment]
> not sure what you mean, which error?
mine is race error.

Talking about travis log: https://gist.github.com/iwanbk/5ce035d7d8e124d2c2c78d8479526bcb
I don't see any error, although there is a package that failed. I don't know why

**Comment by iwanbk** [comment]
Closing it because duplicate of https://github.com/zero-os/0-stor/tree/cli_delete

**Comment by iwanbk** [comment]
keep the branch until #250 fixed

**Pull request closed without merging**
